<header class="row cabecalho">
</header>
<section class="row">	
	<div class="col-sm-4 col-md-3 col-lg-3">
	</div>
	<div class="col-sm-4 col-md-6 col-lg-6">	
	  <div  class="card" > 
		 <div class="card-body">
		  <h1>Busca Funcionários</h1>
		  <br>
		  <br>
			<form>
			  <div class="form-group row">
			    <div class="col-sm-12">
				  <div class="input-group mb-2">
					 <div class="input-group-prepend">
					   <div class="input-group-text">E-mail</div>
					 </div>
					 <input  class="form-control" id="preco" placeholder="E-mail do Funcionário">
				  </div>
				</div>
			  </div>
				<br>                            
			    <br>
			   <button type="button" class="btn btn-outline-success">Buscar Funcionário</button>
			</form>
			</div>
	  </div>
	</div>
	<div class="col-sm-4 col-md-3 col-lg-3">		
	</div>
<footer>
</footer>