<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="assets/img/apple-icon.png" />
    <link rel="icon" href="assets/img/favicon.png" />
    <title>
        <?= $title ?>
    </title>
    <!--  Arquivos CSS  -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" />
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="assets/css/layout.css" rel="stylesheet" type="text/css" />
    
    <link rel="stylesheet" href="assets/css/font-awesome.min.css" type="text/css">
</head>

<body class="container-fluid">
    <header class="row cabecalho">
    </header>
    <section class="row">
    <div class="col-sm-4 col-md-3 col-lg-3">
			
		</div>
		<div class="col-sm-4 col-md-6 col-lg-6">
            <?php $this->controller->renderView(); ?>
		</div>
		<div class="col-sm-4 col-md-3 col-lg-3">
		</div>
    </section>
    <!--  Arquivos JS  -->
    <script src="assets/js/" type="text/javascript"></script>
</body>

</html>
